### ISSUE TITLE
Timeout while connecting shop to WP plugin

### ISSUE THREAD

**Issue by pitkane** [ePages-de/ePages-wordpress-plugin#5]
# Problem:

While connecting epages-online-shop plugin to Wordpress site, (sometimes) slowly responding REST API connection times out, and throws an "http_request_failed" error. Default timeout length for wp_remote_get function is 5 seconds, which is too low. 

https://github.com/ePages-de/ePages-wordpress-plugin/blob/master/functions/options_page.php#L19

WP version: 4.6.1-sv_SE 
epages-online-shop: 5.0.10
# Solution:

Increase wp_remote_get timeout length to e.g. 15 seconds

https://codex.wordpress.org/Function_Reference/wp_remote_get

```
static $epages_api_http_options = array(
  "headers" => array(
    "Accept"        => "application/vnd.epages.v1+json"
  ),
  "user-agent" => "epages-WP",
  "timeout" => "15"
);
```
# Logs:

```
PHP message: [EPAGES] Trying to validate shop URL: https://secure.vilkasgroup.com/rs/shops/mikko01/
PHP message: [EPAGES] WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => Operation timed out after 5000 milliseconds with 0 bytes received
                )

        )

    [error_data] => Array
        (
        )

)
```

**Comment by unaitxu** [comment]
Fixed on 44fa9d51c99fb4b23d6ed3d4702d5d4a2e0656f2. Thanks a lot @pitkane!
It'll be live in a couple of days.
